$ANSIBLE_VAULT;1.1;AES256
34343965646266393438316136323466633233633338373435613865336636326133316333343333
6565623064656534393633643739313663613434363565620a363665623462333231636535313834
30366635313130393766363035343166376639346433393564366166653463666639303062633136
6637393939616565350a633064303531353039363035306361636336393634613466313263383962
34323737323563666531656636653264383830633339373564666234363664333866336533336638
61343730346134663439393933313365326261383534373462633338396662303662623636613861
37613263613439376166666130663766303035306266306465386436646533656265376231613032
61646433323466366662666433376161323062613237663032353332313863366163343833316563
32623939366364396232663066666430643937636462306265653265666632323233343061346239
62383563323634306433373331306166363735646266366137633531653339363633643264633934
65306635363636303634333266643031313631663863666331393134383836323835316138383030
39663231343331353663623264653433323531343137653036373634663365373764336536306138
32623235343261663266666534663838333166643665303834633762636638313563333263383932
3732323662663462653962353537656162353266313131636336
