$ANSIBLE_VAULT;1.2;AES256;raspberry_water_system
31666166666437613435383832353036643461313831336534303435373661633563383431323136
6137303061653433393838336265623031336264316362650a653462353539356662333961326335
32373564303766393232666636626466646237333365353666386561316236633934373937376533
6237323635366339620a313830626163333331343037316363396139613062383730623861303837
31623733663966663836656532343365353262393539313430343534353630363737636133366464
36333462626262376165353361663661393733623732396530623332306134353962613361326236
61653131626465376165356465353263333761663561363363653663333134393839666462636564
65356336316163353362333962353563626532613738336561316537313262373439356635353635
66393065666338393833333438626333653139363335373566343334666433653763393135646261
31373762346534303066333433363238363862336462373733646564653236663435613463393933
39303765366465646165633336316132336135356532343433346163323662363261636362353130
65653031353131363938646339623966613764326666666339626534363431623266326366326162
34356138343334393438333739376134626239363539336537363736326536626662
