$ANSIBLE_VAULT;1.2;AES256;raspberry_water_system
62376364353363383364636138363631653735373434313930373433373664653961356337313130
3961316366653035326466396464306135343430396362330a343131363739626362316639326362
36356634333839383432633862303065363066333931323339326533656263616665323431333437
3130383165653330360a313137333939306438313938653737353837393533333137346538326139
39636530616630353732383161346265386639333364353464623238323638336337323734346462
31646162313063666364366530623830646233363231663031313434323834356236353137623130
65393763376262333963346263353163666363396666313335616137393037343031323264623165
31316433333537356261333965353963363361333064333836303539336338336333343633376166
35323064653965363134306638643137373935336235313565626535653965366130396539386363
61613038376432646134386662326664656134666664396566636462626132323134373564653762
61613063376166373737303763653534303938386263396133393132626130306332343766323330
65626163613239383235303138663163343661633039623836383332313662393566303964333961
32396234393437313632393733323162313134666661373830326635663366666637
