$ANSIBLE_VAULT;1.2;AES256;raspberry_water_system
38633934613033366231666530323661656162333832633664353264343431356234313336343639
6138333638343830646163366164646264356636316234610a656536353236383436336265323138
38303730393839366538633632613961653630623764323266623862373931393163363766656262
3266393438633539380a646139356162373763633166313539343436623964356232663537353735
63306662363535336562643139636461343762306534363137393866666537366433653330343262
38613838363033646336306564393262343832386333393338363663333435303430656334626631
66666161333965356232626634663031336135343035653264623062656633333030396231636530
38306330616139316634376366663534353835666264663261353931666236396161663134663565
61333731663962616661616231313264623135633864653039353336626337383434663633326534
34386266643662366437643865626265616163363536653633663866346235323631643234386161
32616233653139656135303562623131663463343237313561326230356233383466616134383437
32303561323062623336656361613364336566373332653365356231633031373637663464363932
33353863656539313333616665313464663431653139383466323663636639643831
